import { OpenRouterModel, SampleVideo } from './types';

export const OPENROUTER_MODELS: OpenRouterModel[] = [
  {
    id: 'meta-llama/llama-3.3-70b-instruct:free',
    name: 'Llama 3.3 70B (Free)',
    contextLength: 128000,
    isFree: true,
    description: 'Zero-cost flagship open-source model through OpenRouter free tier.',
    recommended: true,
  },
  {
    id: 'deepseek/deepseek-r1:free',
    name: 'DeepSeek R1 (Free)',
    contextLength: 128000,
    isFree: true,
    description: 'Free tier reasoning model on OpenRouter.',
    recommended: true,
  },
  {
    id: 'google/gemini-2.0-flash-exp:free',
    name: 'Gemini 2.0 Flash Exp (Free)',
    contextLength: 1048576,
    isFree: true,
    description: 'Free experimental 1M context window model on OpenRouter.',
    recommended: true,
  },
  {
    id: 'deepseek/deepseek-chat',
    name: 'DeepSeek V3 (Chat)',
    contextLength: 64000,
    isFree: false,
    description: 'Extremely strong analytical reasoning & structured summaries at lowest cost.',
    recommended: true,
  },
  {
    id: 'meta-llama/llama-3.3-70b-instruct',
    name: 'Llama 3.3 70B Instruct',
    contextLength: 128000,
    isFree: false,
    description: 'Flagship Meta open-weights model with 128k context window.',
  },
  {
    id: 'deepseek/deepseek-r1',
    name: 'DeepSeek R1 (Reasoning)',
    contextLength: 128000,
    isFree: false,
    description: 'Chain-of-thought reasoning powerhouse for exhaustive technical breakdowns.',
  },
  {
    id: 'google/gemini-2.0-flash-001',
    name: 'Google Gemini 2.0 Flash',
    contextLength: 1048576,
    isFree: false,
    description: 'Massive 1,000,000 token context window. Ideal for 3+ hour podcasts & transcripts.',
  },
  {
    id: 'anthropic/claude-3.5-sonnet',
    name: 'Claude 3.5 Sonnet',
    contextLength: 200000,
    isFree: false,
    description: 'Top-tier prose synthesis, nuanced comprehension, and pristine summaries.',
  },
  {
    id: 'qwen/qwen-2.5-72b-instruct',
    name: 'Qwen 2.5 72B Instruct',
    contextLength: 128000,
    isFree: false,
    description: 'Alibaba Cloud open-weights powerhouse with exceptional multilingual synthesis.',
  },
  {
    id: 'mistralai/mistral-large-2411',
    name: 'Mistral Large 2',
    contextLength: 128000,
    isFree: false,
    description: 'Premier European frontier model for structured editorial synopses.',
  },
];

export const SAMPLE_VIDEOS: SampleVideo[] = [
  {
    id: 'UF8uR6Z6KLc',
    title: 'Steve Jobs 2005 Stanford Commencement Address',
    channel: 'Stanford University',
    duration: '15:04',
    category: 'Inspiration & Leadership',
    url: 'https://www.youtube.com/watch?v=UF8uR6Z6KLc',
    sourceType: 'youtube',
    badge: 'YouTube',
  },
  {
    id: 'aircAruvnKk',
    title: 'But what is a neural network? | Chapter 1, Deep Learning',
    channel: '3Blue1Brown',
    duration: '19:13',
    category: 'Machine Learning',
    url: 'https://www.youtube.com/watch?v=aircAruvnKk',
    sourceType: 'youtube',
    badge: 'YouTube',
  },
  {
    id: '094y1Z2wpJg',
    title: 'The Simplest Math Problem No One Can Solve',
    channel: 'Veritasium',
    duration: '22:08',
    category: 'Mathematics & Science',
    url: 'https://www.youtube.com/watch?v=094y1Z2wpJg',
    sourceType: 'youtube',
    badge: 'YouTube',
  },
  {
    id: 'sir_ken_robinson_do_schools_kill_creativity',
    title: 'Do Schools Kill Creativity?',
    channel: 'Sir Ken Robinson (TED Talks)',
    duration: '19:24',
    category: 'Education & Creativity',
    url: 'https://www.ted.com/talks/sir_ken_robinson_do_schools_kill_creativity',
    sourceType: 'ted',
    badge: 'TED Talk',
  },
  {
    id: '76979871',
    title: 'The Maker (Award-Winning Stop Motion)',
    channel: 'Zealous Creative (Vimeo)',
    duration: '05:30',
    category: 'Cinema & Art',
    url: 'https://vimeo.com/76979871',
    sourceType: 'vimeo',
    badge: 'Vimeo',
  },
  {
    id: 'huberman_focus_podcast',
    title: 'Huberman Lab: Science of Focus, Brain Energy & Deep Work',
    channel: 'Scicomm Media (Podcast RSS)',
    duration: '45:10',
    category: 'Neuroscience & Health',
    url: 'https://feeds.megaphone.fm/hubermanlab',
    sourceType: 'podcast_rss',
    badge: 'Podcast RSS',
  },
  {
    id: 'apollo11_lunar_landing',
    title: 'Apollo 11: "The Eagle Has Landed" (Historic Lunar Descent)',
    channel: 'NASA Historical Audio Archive',
    duration: '06:12',
    category: 'History & Spaceflight',
    url: 'https://archive.org/download/Apollo11Audio/11_04_06_45_EagleLanded.mp3',
    sourceType: 'direct_audio',
    badge: 'Direct Audio',
  },
];

export const DEFAULT_SUMMARY_CONFIG = {
  provider: 'openrouter' as const,
  openRouterKey: '',
  model: 'meta-llama/llama-3.3-70b-instruct:free',
  summaryType: 'massive' as const,
  detailLevel: 'massive' as const,
  includeTimestamps: true,
};

export const SUMMARY_PRESETS: Array<{
  id: 'massive' | 'chronological' | 'concepts' | 'actionable' | 'study_guide';
  label: string;
  shortLabel: string;
  iconName: string;
  description: string;
}> = [
  {
    id: 'massive',
    label: 'Complete Story & Full Breakdown',
    shortLabel: 'Complete Guide',
    iconName: 'Sparkles',
    description: 'Walks through the whole video in natural, everyday English—covering the big picture, stories, quotes, and what you can actually use.',
  },
  {
    id: 'chronological',
    label: 'Moment-by-Moment Timeline',
    shortLabel: 'Step-by-Step Timeline',
    iconName: 'Clock',
    description: 'Follows the video from start to finish with [MM:SS] timestamps for every story, example, and topic change.',
  },
  {
    id: 'concepts',
    label: 'Ideas & Examples Explained Simply',
    shortLabel: 'Main Ideas',
    iconName: 'Layers',
    description: 'Breaks down the main ideas, how things work, and real-world examples in plain, clear language.',
  },
  {
    id: 'actionable',
    label: 'Practical Steps & How-To Guide',
    shortLabel: 'Practical Steps',
    iconName: 'CheckCircle2',
    description: 'Focuses on what you can actually do next—step-by-step habits, helpful checklists, and common mistakes to avoid.',
  },
  {
    id: 'study_guide',
    label: 'Easy Study Notes & Q&A',
    shortLabel: 'Study Notes & Q&A',
    iconName: 'GraduationCap',
    description: 'Helpful word definitions, common questions with clear answers, and quick review cards.',
  },
];

import { ThemeId } from './types';

export interface ThemeConfig {
  id: ThemeId;
  name: string;
  icon: string;
  canvasHex?: string;
  surfaceHex?: string;
  category?: 'daylight' | 'dark';
  description: string;
  pageBg: string;
  cardBg: string;
  headerBg: string;
  border: string;
  borderLight: string;
  textPrimary: string;
  textSecondary: string;
  textMuted: string;
  accent: string;
  accentBg: string;
  accentBorder: string;
  primaryButton: string;
  secondaryButton: string;
  inputBg: string;
  inputBorder: string;
  proseClass: string;
  bannerBg: string;
}

export const APP_THEMES: Record<ThemeId, ThemeConfig> = {
  sepia: {
    id: 'sepia',
    name: 'Warm Sepia',
    icon: '#b45309',
    canvasHex: '#fbf7ee',
    surfaceHex: '#f5edd9',
    category: 'daylight',
    description: 'Soft warm reading tone, easy on eyes (Default)',
    pageBg: 'bg-[#fbf7ee]',
    cardBg: 'bg-[#f5edd9]',
    headerBg: 'bg-[#f5edd9]/95',
    border: 'border-[#dfd2b5]',
    borderLight: 'border-[#e8deca]',
    textPrimary: 'text-[#382d1f]',
    textSecondary: 'text-[#5f4f39]',
    textMuted: 'text-[#8c775a]',
    accent: 'text-amber-800',
    accentBg: 'bg-amber-100/60',
    accentBorder: 'border-amber-300',
    primaryButton: 'bg-[#84532a] hover:bg-[#6e4320] text-white shadow-[#dfd2b5]',
    secondaryButton: 'bg-[#ede3ce] hover:bg-[#e4d8c0] text-[#382d1f] border-[#dfd2b5]',
    inputBg: 'bg-[#fdfbf6]',
    inputBorder: 'border-[#dfd2b5]',
    proseClass: 'prose-stone',
    bannerBg: 'bg-amber-50/80 border-amber-200',
  },
  light: {
    id: 'light',
    name: 'Archival Ivory',
    icon: '#3b5998',
    canvasHex: '#f6f4ef',
    surfaceHex: '#efece4',
    category: 'daylight',
    description: 'Natural unbleached cotton book stock with charcoal ink',
    pageBg: 'bg-[#f6f4ef]',
    cardBg: 'bg-[#efece4]',
    headerBg: 'bg-[#f6f4ef]/95',
    border: 'border-[#ddd8cc]',
    borderLight: 'border-[#e6e1d6]',
    textPrimary: 'text-[#23211d]',
    textSecondary: 'text-[#4a463f]',
    textMuted: 'text-[#787268]',
    accent: 'text-[#2b4c7e]',
    accentBg: 'bg-[#2b4c7e]/10',
    accentBorder: 'border-[#2b4c7e]/25',
    primaryButton: 'bg-[#2b4c7e] hover:bg-[#213b63] text-white shadow-sm',
    secondaryButton: 'bg-[#e6e2d8] hover:bg-[#dcd7cb] text-[#23211d] border-[#d2ccc0]',
    inputBg: 'bg-[#faf9f5]',
    inputBorder: 'border-[#d6d0c4]',
    proseClass: 'prose-stone',
    bannerBg: 'bg-[#eef2f7] border-[#cbd6e4]',
  },
  solarized: {
    id: 'solarized',
    name: 'Solarized Parchment',
    icon: '#268bd2',
    canvasHex: '#fdf6e3',
    surfaceHex: '#eee8d5',
    category: 'daylight',
    description: 'Calibrated warm daylight laboratory parchment for zero eye strain',
    pageBg: 'bg-[#fdf6e3]',
    cardBg: 'bg-[#eee8d5]',
    headerBg: 'bg-[#eee8d5]/95',
    border: 'border-[#d8d1be]',
    borderLight: 'border-[#e4decb]',
    textPrimary: 'text-[#073642]',
    textSecondary: 'text-[#475b62]',
    textMuted: 'text-[#657b83]',
    accent: 'text-[#268bd2]',
    accentBg: 'bg-[#268bd2]/12',
    accentBorder: 'border-[#268bd2]/30',
    primaryButton: 'bg-[#268bd2] hover:bg-[#1f76b4] text-white shadow-sm',
    secondaryButton: 'bg-[#e4decb] hover:bg-[#d8d1be] text-[#073642] border-[#d0c8b4]',
    inputBg: 'bg-[#fefbf1]',
    inputBorder: 'border-[#d8d1be]',
    proseClass: 'prose-stone',
    bannerBg: 'bg-[#eee8d5] border-[#d5ceb8]',
  },
  alabaster: {
    id: 'alabaster',
    name: 'E-Ink Matte Pearl',
    icon: '#2f5d62',
    canvasHex: '#f1f1ed',
    surfaceHex: '#e7e7e1',
    category: 'daylight',
    description: 'Low-glare e-reader matte paper with soft carbon ink',
    pageBg: 'bg-[#f1f1ed]',
    cardBg: 'bg-[#e7e7e1]',
    headerBg: 'bg-[#ebebe6]/95',
    border: 'border-[#d2d2ca]',
    borderLight: 'border-[#ddddD6]',
    textPrimary: 'text-[#222425]',
    textSecondary: 'text-[#45484a]',
    textMuted: 'text-[#6e7275]',
    accent: 'text-[#2f5d62]',
    accentBg: 'bg-[#2f5d62]/12',
    accentBorder: 'border-[#2f5d62]/30',
    primaryButton: 'bg-[#2f5d62] hover:bg-[#24484c] text-white shadow-sm',
    secondaryButton: 'bg-[#dfdfd8] hover:bg-[#d4d4cc] text-[#222425] border-[#c8c8c0]',
    inputBg: 'bg-[#f7f7f4]',
    inputBorder: 'border-[#d2d2ca]',
    proseClass: 'prose-stone',
    bannerBg: 'bg-[#e6ecec] border-[#c4d4d5]',
  },
  matcha: {
    id: 'matcha',
    name: 'Botanical Sage Paper',
    icon: '#356854',
    canvasHex: '#f2f4ef',
    surfaceHex: '#e7ebe2',
    category: 'daylight',
    description: 'Restful herbarium sage linen that relaxes optic nerves',
    pageBg: 'bg-[#f2f4ef]',
    cardBg: 'bg-[#e7ebe2]',
    headerBg: 'bg-[#e7ebe2]/95',
    border: 'border-[#cdd5c6]',
    borderLight: 'border-[#d9e0d3]',
    textPrimary: 'text-[#212922]',
    textSecondary: 'text-[#434f44]',
    textMuted: 'text-[#6a786b]',
    accent: 'text-[#2d5e46]',
    accentBg: 'bg-[#2d5e46]/12',
    accentBorder: 'border-[#2d5e46]/25',
    primaryButton: 'bg-[#356854] hover:bg-[#295242] text-white shadow-sm',
    secondaryButton: 'bg-[#dce2d6] hover:bg-[#d0d8c9] text-[#212922] border-[#c5cfc0]',
    inputBg: 'bg-[#f8faf6]',
    inputBorder: 'border-[#cdd5c6]',
    proseClass: 'prose-stone',
    bannerBg: 'bg-[#e5ede7] border-[#c5d6ca]',
  },
  rose: {
    id: 'rose',
    name: 'Warm Limestone Clay',
    icon: '#9a4b3e',
    canvasHex: '#f6f2ef',
    surfaceHex: '#ede6e1',
    category: 'daylight',
    description: 'Architectural travertine & muted terracotta editorial paper',
    pageBg: 'bg-[#f6f2ef]',
    cardBg: 'bg-[#ede6e1]',
    headerBg: 'bg-[#ede6e1]/95',
    border: 'border-[#d9cfc8]',
    borderLight: 'border-[#e4dcd6]',
    textPrimary: 'text-[#2d2522]',
    textSecondary: 'text-[#544742]',
    textMuted: 'text-[#807069]',
    accent: 'text-[#9a4b3e]',
    accentBg: 'bg-[#9a4b3e]/10',
    accentBorder: 'border-[#9a4b3e]/25',
    primaryButton: 'bg-[#8f4438] hover:bg-[#76372d] text-white shadow-sm',
    secondaryButton: 'bg-[#e3dad4] hover:bg-[#d8cdc6] text-[#2d2522] border-[#cfc3bb]',
    inputBg: 'bg-[#faf7f5]',
    inputBorder: 'border-[#d9cfc8]',
    proseClass: 'prose-stone',
    bannerBg: 'bg-[#f3e8e5] border-[#dec8c2]',
  },
  nordlight: {
    id: 'nordlight',
    name: 'Nordic Snow Slate',
    icon: '#4c6ef5',
    canvasHex: '#eef1f6',
    surfaceHex: '#e4e9f0',
    category: 'daylight',
    description: 'Cool Scandinavian architectural paper with crisp slate ink',
    pageBg: 'bg-[#eef1f6]',
    cardBg: 'bg-[#e4e9f0]',
    headerBg: 'bg-[#e4e9f0]/95',
    border: 'border-[#cdd5e0]',
    borderLight: 'border-[#d8dfe9]',
    textPrimary: 'text-[#242933]',
    textSecondary: 'text-[#434c5e]',
    textMuted: 'text-[#6c7689]',
    accent: 'text-[#3b5bdb]',
    accentBg: 'bg-[#3b5bdb]/10',
    accentBorder: 'border-[#3b5bdb]/25',
    primaryButton: 'bg-[#3b5bdb] hover:bg-[#2f4bc4] text-white shadow-sm',
    secondaryButton: 'bg-[#dae0ea] hover:bg-[#cfd7e3] text-[#242933] border-[#c4cddb]',
    inputBg: 'bg-[#f5f7fa]',
    inputBorder: 'border-[#cdd5e0]',
    proseClass: 'prose-stone',
    bannerBg: 'bg-[#e3eaf4] border-[#c3d1e6]',
  },
  midnight: {
    id: 'midnight',
    name: 'Graphite Studio',
    icon: '#6b8afd',
    canvasHex: '#17191e',
    surfaceHex: '#1f2229',
    category: 'dark',
    description: 'Neutral matte graphite workspace with soft alabaster text',
    pageBg: 'bg-[#17191e]',
    cardBg: 'bg-[#1f2229]',
    headerBg: 'bg-[#1b1e24]/95',
    border: 'border-[#2c303a]',
    borderLight: 'border-[#262a33]',
    textPrimary: 'text-[#e3e6ed]',
    textSecondary: 'text-[#b2b8c6]',
    textMuted: 'text-[#7d8597]',
    accent: 'text-[#7c9aff]',
    accentBg: 'bg-[#7c9aff]/12',
    accentBorder: 'border-[#7c9aff]/30',
    primaryButton: 'bg-[#4c6ef5] hover:bg-[#4263eb] text-white shadow-sm',
    secondaryButton: 'bg-[#262a34] hover:bg-[#2f3440] text-[#c8cdd8] border-[#363b48]',
    inputBg: 'bg-[#14161b]',
    inputBorder: 'border-[#2e333d]',
    proseClass: 'prose-invert',
    bannerBg: 'bg-[#1e2436] border-[#333f5e]',
  },
  coffee: {
    id: 'coffee',
    name: 'Gruvbox Warm Dark',
    icon: '#d79921',
    canvasHex: '#1d2021',
    surfaceHex: '#282828',
    category: 'dark',
    description: 'Low-blue-light warm charcoal & parchment ink for late-night work',
    pageBg: 'bg-[#1d2021]',
    cardBg: 'bg-[#282828]',
    headerBg: 'bg-[#242424]/95',
    border: 'border-[#3c3836]',
    borderLight: 'border-[#32302f]',
    textPrimary: 'text-[#ebdbb2]',
    textSecondary: 'text-[#d5c4a1]',
    textMuted: 'text-[#928374]',
    accent: 'text-[#fabd2f]',
    accentBg: 'bg-[#d79921]/15',
    accentBorder: 'border-[#d79921]/35',
    primaryButton: 'bg-[#b57614] hover:bg-[#9d6510] text-[#fbf1c7] font-semibold shadow-sm',
    secondaryButton: 'bg-[#32302f] hover:bg-[#3c3836] text-[#d5c4a1] border-[#504945]',
    inputBg: 'bg-[#181a1b]',
    inputBorder: 'border-[#3c3836]',
    proseClass: 'prose-invert',
    bannerBg: 'bg-[#2d2820] border-[#504332]',
  },
  nord: {
    id: 'nord',
    name: 'Nordic Polar Dark',
    icon: '#88c0d0',
    canvasHex: '#242933',
    surfaceHex: '#2e3440',
    category: 'dark',
    description: 'Authentic Arctic slate-blue with soft snow-storm contrast',
    pageBg: 'bg-[#242933]',
    cardBg: 'bg-[#2e3440]',
    headerBg: 'bg-[#292e39]/95',
    border: 'border-[#3b4252]',
    borderLight: 'border-[#353c4a]',
    textPrimary: 'text-[#eceff4]',
    textSecondary: 'text-[#d8dee9]',
    textMuted: 'text-[#9099ab]',
    accent: 'text-[#88c0d0]',
    accentBg: 'bg-[#88c0d0]/12',
    accentBorder: 'border-[#88c0d0]/30',
    primaryButton: 'bg-[#5e81ac] hover:bg-[#52729a] text-white shadow-sm',
    secondaryButton: 'bg-[#353c4a] hover:bg-[#3b4252] text-[#d8dee9] border-[#434c5e]',
    inputBg: 'bg-[#20242d]',
    inputBorder: 'border-[#3b4252]',
    proseClass: 'prose-invert',
    bannerBg: 'bg-[#2b3442] border-[#435269]',
  },
  forest: {
    id: 'forest',
    name: 'Everforest Dark',
    icon: '#83c092',
    canvasHex: '#1e2326',
    surfaceHex: '#272e33',
    category: 'dark',
    description: 'Organic woodland mineral slate with warm wheat typography',
    pageBg: 'bg-[#1e2326]',
    cardBg: 'bg-[#272e33]',
    headerBg: 'bg-[#232a2e]/95',
    border: 'border-[#374145]',
    borderLight: 'border-[#2e383c]',
    textPrimary: 'text-[#d3c6aa]',
    textSecondary: 'text-[#b8b4a6]',
    textMuted: 'text-[#859289]',
    accent: 'text-[#83c092]',
    accentBg: 'bg-[#83c092]/12',
    accentBorder: 'border-[#83c092]/30',
    primaryButton: 'bg-[#4f8a62] hover:bg-[#437854] text-white shadow-sm',
    secondaryButton: 'bg-[#2e383c] hover:bg-[#374145] text-[#d3c6aa] border-[#414b50]',
    inputBg: 'bg-[#1a1f22]',
    inputBorder: 'border-[#374145]',
    proseClass: 'prose-invert',
    bannerBg: 'bg-[#24302c] border-[#3a4f46]',
  },
  ocean: {
    id: 'ocean',
    name: 'Oxford Maritime Slate',
    icon: '#569cd6',
    canvasHex: '#141b24',
    surfaceHex: '#1c2531',
    category: 'dark',
    description: 'Deep nautical slate with calm cerulean and mist-grey ink',
    pageBg: 'bg-[#141b24]',
    cardBg: 'bg-[#1c2531]',
    headerBg: 'bg-[#17202b]/95',
    border: 'border-[#2a3748]',
    borderLight: 'border-[#232f3e]',
    textPrimary: 'text-[#dce3ec]',
    textSecondary: 'text-[#aeb9c7]',
    textMuted: 'text-[#768599]',
    accent: 'text-[#6cb6ff]',
    accentBg: 'bg-[#6cb6ff]/12',
    accentBorder: 'border-[#6cb6ff]/30',
    primaryButton: 'bg-[#316dca] hover:bg-[#295eb0] text-white shadow-sm',
    secondaryButton: 'bg-[#232e3d] hover:bg-[#2b384a] text-[#c5d0de] border-[#334357]',
    inputBg: 'bg-[#11171f]',
    inputBorder: 'border-[#2a3748]',
    proseClass: 'prose-invert',
    bannerBg: 'bg-[#1a2636] border-[#2d4461]',
  },
  sunset: {
    id: 'sunset',
    name: 'Obsidian Warm Quartz',
    icon: '#c48b71',
    canvasHex: '#1b191c',
    surfaceHex: '#242126',
    category: 'dark',
    description: 'Muted mineral basalt with warm sandstone & copper accents',
    pageBg: 'bg-[#1b191c]',
    cardBg: 'bg-[#242126]',
    headerBg: 'bg-[#201d22]/95',
    border: 'border-[#353038]',
    borderLight: 'border-[#2d2930]',
    textPrimary: 'text-[#e6e1e8]',
    textSecondary: 'text-[#bdb5c2]',
    textMuted: 'text-[#877e8c]',
    accent: 'text-[#d99b7e]',
    accentBg: 'bg-[#c48b71]/14',
    accentBorder: 'border-[#c48b71]/30',
    primaryButton: 'bg-[#9c634b] hover:bg-[#87533d] text-white shadow-sm',
    secondaryButton: 'bg-[#2d2930] hover:bg-[#36313a] text-[#cfc8d4] border-[#3f3944]',
    inputBg: 'bg-[#161417]',
    inputBorder: 'border-[#353038]',
    proseClass: 'prose-invert',
    bannerBg: 'bg-[#2a2223] border-[#4a3938]',
  },
  cyberpunk: {
    id: 'cyberpunk',
    name: 'Tokyo Night Studio',
    icon: '#7aa2f7',
    canvasHex: '#1a1b26',
    surfaceHex: '#24283b',
    category: 'dark',
    description: 'Refined Japanese developer dusk palette with soft indigo ink',
    pageBg: 'bg-[#1a1b26]',
    cardBg: 'bg-[#24283b]',
    headerBg: 'bg-[#1f2335]/95',
    border: 'border-[#323852]',
    borderLight: 'border-[#292e42]',
    textPrimary: 'text-[#c0caf5]',
    textSecondary: 'text-[#a9b1d6]',
    textMuted: 'text-[#6c759c]',
    accent: 'text-[#7aa2f7]',
    accentBg: 'bg-[#7aa2f7]/12',
    accentBorder: 'border-[#7aa2f7]/30',
    primaryButton: 'bg-[#3d59a1] hover:bg-[#344d8c] text-white shadow-sm',
    secondaryButton: 'bg-[#292e42] hover:bg-[#323852] text-[#a9b1d6] border-[#3b4261]',
    inputBg: 'bg-[#16161e]',
    inputBorder: 'border-[#323852]',
    proseClass: 'prose-invert',
    bannerBg: 'bg-[#20263d] border-[#354066]',
  },
  oled: {
    id: 'oled',
    name: 'Dimmed Carbon Matte',
    icon: '#529e72',
    canvasHex: '#121416',
    surfaceHex: '#1a1d20',
    category: 'dark',
    description: 'Anti-halation deep carbon with subdued sage & silver ink',
    pageBg: 'bg-[#121416]',
    cardBg: 'bg-[#1a1d20]',
    headerBg: 'bg-[#16181b]/95',
    border: 'border-[#282c30]',
    borderLight: 'border-[#212529]',
    textPrimary: 'text-[#dcdfe4]',
    textSecondary: 'text-[#a6adb5]',
    textMuted: 'text-[#707780]',
    accent: 'text-[#68b388]',
    accentBg: 'bg-[#529e72]/12',
    accentBorder: 'border-[#529e72]/30',
    primaryButton: 'bg-[#3d7a57] hover:bg-[#326648] text-white shadow-sm',
    secondaryButton: 'bg-[#212529] hover:bg-[#2a2f34] text-[#c2c7ce] border-[#32373d]',
    inputBg: 'bg-[#0e1012]',
    inputBorder: 'border-[#282c30]',
    proseClass: 'prose-invert',
    bannerBg: 'bg-[#17241d] border-[#294235]',
  },
};

