import { OpenRouterModel, SampleVideo } from './types';

export const OPENROUTER_MODELS: OpenRouterModel[] = [
  {
    id: 'meta-llama/llama-3.3-70b-instruct:free',
    name: 'Llama 3.3 70B (Free)',
    contextLength: 128000,
    isFree: true,
    description: 'Zero-cost flagship open-source model through OpenRouter free tier.',
    recommended: true,
  },
  {
    id: 'deepseek/deepseek-r1:free',
    name: 'DeepSeek R1 (Free)',
    contextLength: 128000,
    isFree: true,
    description: 'Free tier reasoning model on OpenRouter.',
    recommended: true,
  },
  {
    id: 'google/gemini-2.0-flash-exp:free',
    name: 'Gemini 2.0 Flash Exp (Free)',
    contextLength: 1048576,
    isFree: true,
    description: 'Free experimental 1M context window model on OpenRouter.',
    recommended: true,
  },
  {
    id: 'deepseek/deepseek-chat',
    name: 'DeepSeek V3 (Chat)',
    contextLength: 64000,
    isFree: false,
    description: 'Extremely strong analytical reasoning & structured summaries at lowest cost.',
    recommended: true,
  },
  {
    id: 'meta-llama/llama-3.3-70b-instruct',
    name: 'Llama 3.3 70B Instruct',
    contextLength: 128000,
    isFree: false,
    description: 'Flagship Meta open-weights model with 128k context window.',
  },
  {
    id: 'deepseek/deepseek-r1',
    name: 'DeepSeek R1 (Reasoning)',
    contextLength: 128000,
    isFree: false,
    description: 'Chain-of-thought reasoning powerhouse for exhaustive technical breakdowns.',
  },
  {
    id: 'google/gemini-2.0-flash-001',
    name: 'Google Gemini 2.0 Flash',
    contextLength: 1048576,
    isFree: false,
    description: 'Massive 1,000,000 token context window. Ideal for 3+ hour podcasts & transcripts.',
  },
  {
    id: 'anthropic/claude-3.5-sonnet',
    name: 'Claude 3.5 Sonnet',
    contextLength: 200000,
    isFree: false,
    description: 'Top-tier prose synthesis, nuanced comprehension, and pristine summaries.',
  },
  {
    id: 'qwen/qwen-2.5-72b-instruct',
    name: 'Qwen 2.5 72B Instruct',
    contextLength: 128000,
    isFree: false,
    description: 'Alibaba Cloud open-weights powerhouse with exceptional multilingual synthesis.',
  },
  {
    id: 'mistralai/mistral-large-2411',
    name: 'Mistral Large 2',
    contextLength: 128000,
    isFree: false,
    description: 'Premier European frontier model for structured editorial synopses.',
  },
];

export const SAMPLE_VIDEOS: SampleVideo[] = [
  {
    id: 'UF8uR6Z6KLc',
    title: 'Steve Jobs 2005 Stanford Commencement Address',
    channel: 'Stanford University',
    duration: '15:04',
    category: 'Inspiration & Leadership',
    url: 'https://www.youtube.com/watch?v=UF8uR6Z6KLc',
  },
  {
    id: 'aircAruvnKk',
    title: 'But what is a neural network? | Chapter 1, Deep Learning',
    channel: '3Blue1Brown',
    duration: '19:13',
    category: 'Machine Learning',
    url: 'https://www.youtube.com/watch?v=aircAruvnKk',
  },
  {
    id: '094y1Z2wpJg',
    title: 'The Simplest Math Problem No One Can Solve',
    channel: 'Veritasium',
    duration: '22:08',
    category: 'Mathematics & Science',
    url: 'https://www.youtube.com/watch?v=094y1Z2wpJg',
  },
  {
    id: 'dQw4w9WgXcQ',
    title: 'Rick Astley - Never Gonna Give You Up (Official Music Video)',
    channel: 'Rick Astley',
    duration: '03:33',
    category: 'Music & Culture',
    url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
  },
];

export const DEFAULT_SUMMARY_CONFIG = {
  provider: 'openrouter' as const,
  openRouterKey: '',
  model: 'meta-llama/llama-3.3-70b-instruct:free',
  summaryType: 'massive' as const,
  detailLevel: 'massive' as const,
  includeTimestamps: true,
};

export const SUMMARY_PRESETS: Array<{
  id: 'massive' | 'chronological' | 'concepts' | 'actionable' | 'study_guide';
  label: string;
  shortLabel: string;
  iconName: string;
  description: string;
}> = [
  {
    id: 'massive',
    label: 'Complete Story & Full Breakdown',
    shortLabel: 'Complete Guide',
    iconName: 'Sparkles',
    description: 'Walks through the whole video in natural, everyday English—covering the big picture, stories, quotes, and what you can actually use.',
  },
  {
    id: 'chronological',
    label: 'Moment-by-Moment Timeline',
    shortLabel: 'Step-by-Step Timeline',
    iconName: 'Clock',
    description: 'Follows the video from start to finish with [MM:SS] timestamps for every story, example, and topic change.',
  },
  {
    id: 'concepts',
    label: 'Ideas & Examples Explained Simply',
    shortLabel: 'Main Ideas',
    iconName: 'Layers',
    description: 'Breaks down the main ideas, how things work, and real-world examples in plain, clear language.',
  },
  {
    id: 'actionable',
    label: 'Practical Steps & How-To Guide',
    shortLabel: 'Practical Steps',
    iconName: 'CheckCircle2',
    description: 'Focuses on what you can actually do next—step-by-step habits, helpful checklists, and common mistakes to avoid.',
  },
  {
    id: 'study_guide',
    label: 'Easy Study Notes & Q&A',
    shortLabel: 'Study Notes & Q&A',
    iconName: 'GraduationCap',
    description: 'Helpful word definitions, common questions with clear answers, and quick review cards.',
  },
];

import { ThemeId } from './types';

export interface ThemeConfig {
  id: ThemeId;
  name: string;
  icon: string;
  description: string;
  pageBg: string;
  cardBg: string;
  headerBg: string;
  border: string;
  borderLight: string;
  textPrimary: string;
  textSecondary: string;
  textMuted: string;
  accent: string;
  accentBg: string;
  accentBorder: string;
  primaryButton: string;
  secondaryButton: string;
  inputBg: string;
  inputBorder: string;
  proseClass: string;
  bannerBg: string;
}

export const APP_THEMES: Record<ThemeId, ThemeConfig> = {
  midnight: {
    id: 'midnight',
    name: 'Midnight Dark',
    icon: '#6366f1',
    description: 'Deep obsidian and slate with crisp contrast',
    pageBg: 'bg-slate-950',
    cardBg: 'bg-slate-900/90',
    headerBg: 'bg-slate-900/95',
    border: 'border-slate-800',
    borderLight: 'border-slate-700/60',
    textPrimary: 'text-slate-100',
    textSecondary: 'text-slate-300',
    textMuted: 'text-slate-400',
    accent: 'text-indigo-400',
    accentBg: 'bg-indigo-500/10',
    accentBorder: 'border-indigo-500/30',
    primaryButton: 'bg-indigo-600 hover:bg-indigo-500 text-white shadow-indigo-600/25',
    secondaryButton: 'bg-slate-800 hover:bg-slate-700 text-slate-300 border-slate-700',
    inputBg: 'bg-slate-900',
    inputBorder: 'border-slate-700/80',
    proseClass: 'prose-invert',
    bannerBg: 'bg-indigo-950/20 border-indigo-500/30',
  },
  oled: {
    id: 'oled',
    name: 'Pure OLED',
    icon: '#10b981',
    description: 'True pitch-black background with emerald highlights',
    pageBg: 'bg-black',
    cardBg: 'bg-zinc-950',
    headerBg: 'bg-black/95',
    border: 'border-zinc-800',
    borderLight: 'border-zinc-800/80',
    textPrimary: 'text-zinc-100',
    textSecondary: 'text-zinc-300',
    textMuted: 'text-zinc-500',
    accent: 'text-emerald-400',
    accentBg: 'bg-emerald-500/10',
    accentBorder: 'border-emerald-500/30',
    primaryButton: 'bg-emerald-600 hover:bg-emerald-500 text-white shadow-emerald-600/25',
    secondaryButton: 'bg-zinc-900 hover:bg-zinc-800 text-zinc-300 border-zinc-800',
    inputBg: 'bg-zinc-950',
    inputBorder: 'border-zinc-800',
    proseClass: 'prose-invert',
    bannerBg: 'bg-emerald-950/20 border-emerald-500/30',
  },
  nord: {
    id: 'nord',
    name: 'Nordic Frost',
    icon: '#38bdf8',
    description: 'Arctic slate-blue and calm glacier tones',
    pageBg: 'bg-[#1e2430]',
    cardBg: 'bg-[#252c3a]',
    headerBg: 'bg-[#1e2430]/95',
    border: 'border-[#333d4f]',
    borderLight: 'border-[#2f3848]',
    textPrimary: 'text-[#eceff4]',
    textSecondary: 'text-[#d8dee9]',
    textMuted: 'text-[#9aa5b8]',
    accent: 'text-sky-400',
    accentBg: 'bg-sky-400/10',
    accentBorder: 'border-sky-400/30',
    primaryButton: 'bg-sky-600 hover:bg-sky-500 text-white shadow-sky-600/20',
    secondaryButton: 'bg-[#2e3440] hover:bg-[#3b4252] text-[#d8dee9] border-[#434c5e]',
    inputBg: 'bg-[#252c3a]',
    inputBorder: 'border-[#3b4252]',
    proseClass: 'prose-invert',
    bannerBg: 'bg-sky-950/25 border-sky-500/30',
  },
  forest: {
    id: 'forest',
    name: 'Forest Pine',
    icon: '#34d399',
    description: 'Deep woodland green and tranquil sage',
    pageBg: 'bg-[#071410]',
    cardBg: 'bg-[#0c1f19]',
    headerBg: 'bg-[#071410]/95',
    border: 'border-emerald-900/50',
    borderLight: 'border-emerald-800/35',
    textPrimary: 'text-emerald-50',
    textSecondary: 'text-emerald-200/90',
    textMuted: 'text-emerald-400/60',
    accent: 'text-emerald-400',
    accentBg: 'bg-emerald-500/10',
    accentBorder: 'border-emerald-500/30',
    primaryButton: 'bg-emerald-600 hover:bg-emerald-500 text-white shadow-emerald-600/20',
    secondaryButton: 'bg-[#112a22] hover:bg-[#16352b] text-emerald-200 border-emerald-800/50',
    inputBg: 'bg-[#0a1a15]',
    inputBorder: 'border-emerald-800/50',
    proseClass: 'prose-invert',
    bannerBg: 'bg-emerald-950/30 border-emerald-500/30',
  },
  coffee: {
    id: 'coffee',
    name: 'Espresso Roast',
    icon: '#f59e0b',
    description: 'Warm dark cocoa and roasted amber notes',
    pageBg: 'bg-[#16110e]',
    cardBg: 'bg-[#211a15]',
    headerBg: 'bg-[#16110e]/95',
    border: 'border-[#362a22]',
    borderLight: 'border-[#2e231c]',
    textPrimary: 'text-[#f5ebe4]',
    textSecondary: 'text-[#dbc7b8]',
    textMuted: 'text-[#9e8675]',
    accent: 'text-amber-400',
    accentBg: 'bg-amber-500/10',
    accentBorder: 'border-amber-500/30',
    primaryButton: 'bg-amber-600 hover:bg-amber-500 text-slate-950 font-semibold shadow-amber-600/20',
    secondaryButton: 'bg-[#2a211b] hover:bg-[#362a22] text-[#dbc7b8] border-[#3d3027]',
    inputBg: 'bg-[#1c1612]',
    inputBorder: 'border-[#362a22]',
    proseClass: 'prose-invert',
    bannerBg: 'bg-amber-950/25 border-amber-500/30',
  },
  sunset: {
    id: 'sunset',
    name: 'Amethyst Dusk',
    icon: '#c084fc',
    description: 'Twilight plum with warm violet highlights',
    pageBg: 'bg-[#120b1d]',
    cardBg: 'bg-[#1a102a]',
    headerBg: 'bg-[#120b1d]/95',
    border: 'border-purple-900/50',
    borderLight: 'border-purple-800/35',
    textPrimary: 'text-purple-50',
    textSecondary: 'text-purple-200/90',
    textMuted: 'text-purple-400/60',
    accent: 'text-purple-400',
    accentBg: 'bg-purple-500/10',
    accentBorder: 'border-purple-500/30',
    primaryButton: 'bg-purple-600 hover:bg-purple-500 text-white shadow-purple-600/25',
    secondaryButton: 'bg-[#231638] hover:bg-[#2d1c47] text-purple-200 border-purple-800/50',
    inputBg: 'bg-[#170e26]',
    inputBorder: 'border-purple-800/50',
    proseClass: 'prose-invert',
    bannerBg: 'bg-purple-950/30 border-purple-500/30',
  },
  ocean: {
    id: 'ocean',
    name: 'Deep Ocean',
    icon: '#14b8a6',
    description: 'Abyssal marine blue with serene teal accents',
    pageBg: 'bg-[#04141c]',
    cardBg: 'bg-[#08202c]',
    headerBg: 'bg-[#04141c]/95',
    border: 'border-teal-900/50',
    borderLight: 'border-teal-800/35',
    textPrimary: 'text-teal-50',
    textSecondary: 'text-teal-200/90',
    textMuted: 'text-teal-400/60',
    accent: 'text-teal-400',
    accentBg: 'bg-teal-500/10',
    accentBorder: 'border-teal-500/30',
    primaryButton: 'bg-teal-600 hover:bg-teal-500 text-white shadow-teal-600/20',
    secondaryButton: 'bg-[#0d2c3d] hover:bg-[#12394f] text-teal-200 border-teal-800/50',
    inputBg: 'bg-[#071b26]',
    inputBorder: 'border-teal-800/50',
    proseClass: 'prose-invert',
    bannerBg: 'bg-teal-950/30 border-teal-500/30',
  },
  cyberpunk: {
    id: 'cyberpunk',
    name: 'Cyber Navy',
    icon: '#06b6d4',
    description: 'Electric cyan on deep void',
    pageBg: 'bg-[#060913]',
    cardBg: 'bg-[#0d1322]/95',
    headerBg: 'bg-[#080d19]/95',
    border: 'border-cyan-900/50',
    borderLight: 'border-cyan-800/40',
    textPrimary: 'text-cyan-50',
    textSecondary: 'text-cyan-200/90',
    textMuted: 'text-cyan-400/60',
    accent: 'text-cyan-400',
    accentBg: 'bg-cyan-500/10',
    accentBorder: 'border-cyan-500/30',
    primaryButton: 'bg-cyan-500 hover:bg-cyan-400 text-slate-950 font-bold shadow-cyan-500/20',
    secondaryButton: 'bg-slate-900 hover:bg-slate-800 text-cyan-200 border-cyan-800/60',
    inputBg: 'bg-[#070b16]',
    inputBorder: 'border-cyan-800/50',
    proseClass: 'prose-invert',
    bannerBg: 'bg-cyan-950/30 border-cyan-500/30',
  },
  light: {
    id: 'light',
    name: 'Crisp Paper',
    icon: '#4f46e5',
    description: 'Clean paper aesthetic with high legibility',
    pageBg: 'bg-stone-100/90',
    cardBg: 'bg-white',
    headerBg: 'bg-white/95',
    border: 'border-stone-200',
    borderLight: 'border-stone-200/80',
    textPrimary: 'text-stone-900',
    textSecondary: 'text-stone-700',
    textMuted: 'text-stone-500',
    accent: 'text-indigo-600',
    accentBg: 'bg-indigo-50',
    accentBorder: 'border-indigo-200',
    primaryButton: 'bg-indigo-600 hover:bg-indigo-700 text-white shadow-indigo-500/20',
    secondaryButton: 'bg-stone-100 hover:bg-stone-200 text-stone-700 border-stone-300',
    inputBg: 'bg-white',
    inputBorder: 'border-stone-300',
    proseClass: 'prose-stone',
    bannerBg: 'bg-indigo-50/80 border-indigo-200',
  },
  sepia: {
    id: 'sepia',
    name: 'Warm Sepia',
    icon: '#b45309',
    description: 'Soft warm reading tone, easy on eyes',
    pageBg: 'bg-[#fbf7ee]',
    cardBg: 'bg-[#f5edd9]',
    headerBg: 'bg-[#f5edd9]/95',
    border: 'border-[#dfd2b5]',
    borderLight: 'border-[#e8deca]',
    textPrimary: 'text-[#382d1f]',
    textSecondary: 'text-[#5f4f39]',
    textMuted: 'text-[#8c775a]',
    accent: 'text-amber-800',
    accentBg: 'bg-amber-100/60',
    accentBorder: 'border-amber-300',
    primaryButton: 'bg-[#84532a] hover:bg-[#6e4320] text-white shadow-[#dfd2b5]',
    secondaryButton: 'bg-[#ede3ce] hover:bg-[#e4d8c0] text-[#382d1f] border-[#dfd2b5]',
    inputBg: 'bg-[#fdfbf6]',
    inputBorder: 'border-[#dfd2b5]',
    proseClass: 'prose-stone',
    bannerBg: 'bg-amber-50/80 border-amber-200',
  },
  matcha: {
    id: 'matcha',
    name: 'Matcha Cream',
    icon: '#15803d',
    description: 'Soft daylight botanical green paper theme',
    pageBg: 'bg-[#f2f6f0]',
    cardBg: 'bg-[#e7efe3]',
    headerBg: 'bg-[#f2f6f0]/95',
    border: 'border-[#c8d8c0]',
    borderLight: 'border-[#d5e2ce]',
    textPrimary: 'text-[#1c2d19]',
    textSecondary: 'text-[#354f30]',
    textMuted: 'text-[#627c5c]',
    accent: 'text-emerald-800',
    accentBg: 'bg-emerald-100/70',
    accentBorder: 'border-emerald-300',
    primaryButton: 'bg-emerald-700 hover:bg-emerald-800 text-white shadow-emerald-500/15',
    secondaryButton: 'bg-[#dce7d6] hover:bg-[#cfdec8] text-[#1c2d19] border-[#c8d8c0]',
    inputBg: 'bg-[#f9fbf8]',
    inputBorder: 'border-[#c8d8c0]',
    proseClass: 'prose-stone',
    bannerBg: 'bg-emerald-50/80 border-emerald-200',
  },
  rose: {
    id: 'rose',
    name: 'Rose Editorial',
    icon: '#e11d48',
    description: 'Warm blush-ivory daylight paper with rose accents',
    pageBg: 'bg-[#fcf5f6]',
    cardBg: 'bg-[#f7eaed]',
    headerBg: 'bg-[#fcf5f6]/95',
    border: 'border-[#e6cdd2]',
    borderLight: 'border-[#eed9dd]',
    textPrimary: 'text-[#3b1921]',
    textSecondary: 'text-[#5e303b]',
    textMuted: 'text-[#8f5b67]',
    accent: 'text-rose-700',
    accentBg: 'bg-rose-100/70',
    accentBorder: 'border-rose-300',
    primaryButton: 'bg-rose-700 hover:bg-rose-800 text-white shadow-rose-500/15',
    secondaryButton: 'bg-[#f0dde1] hover:bg-[#e6cdd2] text-[#3b1921] border-[#e6cdd2]',
    inputBg: 'bg-[#fffafb]',
    inputBorder: 'border-[#e6cdd2]',
    proseClass: 'prose-stone',
    bannerBg: 'bg-rose-50/80 border-rose-200',
  },
};

